name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Pack
        run: dotnet pack --configuration Release --output . src/EntityFrameworkCore.DataEncryption/EntityFrameworkCore.DataEncryption.csproj
      - name: Add source
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/foys-tech/index.json"
      - name: Publish
        run: dotnet nuget push "Foys-Tech.EntityFrameworkCore.DataEncryption.5.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source github